-- MySQL Script generated by MySQL Workbench
-- Fri Oct 24 08:25:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`classificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classificacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classificacao` (
  `idclassificacao` INT(6) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idclassificacao`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `idlivro` INT(4) UNSIGNED NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `classificacao_idclassificacao` INT(6) NOT NULL,
  UNIQUE INDEX `idlivro_UNIQUE` (`idlivro` ASC) VISIBLE,
  PRIMARY KEY (`idlivro`),
  INDEX `fk_livro_classificacao_idx` (`classificacao_idclassificacao` ASC) VISIBLE,
  CONSTRAINT `fk_livro_classificacao`
    FOREIGN KEY (`classificacao_idclassificacao`)
    REFERENCES `mydb`.`classificacao` (`idclassificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `idautor` INT(6) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro_has_autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livro_has_autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livro_has_autor` (
  `livro_idlivro` INT(4) UNSIGNED NOT NULL,
  `autor_idautor` INT(6) NOT NULL,
  `livro_has_autor_livro_idlivro` INT(4) UNSIGNED NOT NULL,
  `livro_has_autor_autor_idautor` INT(6) NOT NULL,
  PRIMARY KEY (`livro_idlivro`, `autor_idautor`),
  INDEX `fk_livro_has_autor_autor1_idx` (`autor_idautor` ASC) VISIBLE,
  INDEX `fk_livro_has_autor_livro1_idx` (`livro_idlivro` ASC) VISIBLE,
  INDEX `fk_livro_has_autor_livro_has_autor1_idx` (`livro_has_autor_livro_idlivro` ASC, `livro_has_autor_autor_idautor` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_autor_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `mydb`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`autor_idautor`)
    REFERENCES `mydb`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_livro_has_autor1`
    FOREIGN KEY (`livro_has_autor_livro_idlivro` , `livro_has_autor_autor_idautor`)
    REFERENCES `mydb`.`livro_has_autor` (`livro_idlivro` , `autor_idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Editora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Editora` (
  `idEditora` INT(6) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exemplar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Exemplar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Exemplar` (
  `idExemplar` INT(6) NOT NULL,
  `ano` INT(4) NOT NULL,
  `edicao` VARCHAR(50) NOT NULL,
  `tombado` TINYINT NOT NULL,
  `Editora_idEditora` INT NOT NULL,
  `livro_idlivro` INT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`idExemplar`),
  INDEX `fk_Exemplar_Editora1_idx` (`Editora_idEditora` ASC) VISIBLE,
  INDEX `fk_Exemplar_livro1_idx` (`livro_idlivro` ASC) VISIBLE,
  CONSTRAINT `fk_Exemplar_Editora1`
    FOREIGN KEY (`Editora_idEditora`)
    REFERENCES `mydb`.`Editora` (`idEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exemplar_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `mydb`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Leitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Leitor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Leitor` (
  `idLeitor` INT(8) UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `celular` BIGINT(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idLeitor`),
  UNIQUE INDEX `idLeitor_UNIQUE` (`idLeitor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Emprestimo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Emprestimo` (
  `idEmprestimo` INT(6) NOT NULL,
  `data_emprestimo` DATE NOT NULL,
  `data_devolucao` DATE NOT NULL,
  `multa` FLOAT NULL,
  `Exemplar_idExemplar` INT NOT NULL,
  `Leitor_idLeitor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEmprestimo`),
  INDEX `fk_Emprestimo_Exemplar1_idx` (`Exemplar_idExemplar` ASC) VISIBLE,
  INDEX `fk_Emprestimo_Leitor1_idx` (`Leitor_idLeitor` ASC) VISIBLE,
  CONSTRAINT `fk_Emprestimo_Exemplar1`
    FOREIGN KEY (`Exemplar_idExemplar`)
    REFERENCES `mydb`.`Exemplar` (`idExemplar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_Leitor1`
    FOREIGN KEY (`Leitor_idLeitor`)
    REFERENCES `mydb`.`Leitor` (`idLeitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
